name : Remote SSH
on: 
  push:
      branches:
        - main
jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build
          
      - name: Verify build
        run: ls -la public

      - name: Clean Up Old Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            rm -rf site/mainBranch
            mkdir -p site/newBranch

      - name: Copy Files to Remote Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}         
          username: ${{ secrets.USER }}     
          key: ${{ secrets.PRIVATE_KEY }}
          source: "public/*"
          target: "site/newBranch"

      - name: Finalize Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cat ~/.ssh/id_rsa_github.pub | ssh secrets.USER@secrets.HOST 'cat >> ~/.ssh/authorized_keys'
            mv site/newBranch/* site/mainBranch/
            rm -rf site/newBranch
