name : Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build --prefix-paths

      - name: Verify build
        run: ls -la public
      
      - name: Create tar file
        run: |
          mkdir -p /tmp/173971303
          echo "Contents of current directory:"
          ls -la
          echo "Contents of public directory:"
          ls -la public/
      
           # Check for docker-compose.yml in the current directory
          if [ -f "docker-compose.yml" ]; then
            echo "docker-compose.yml found in the current directory."
          else
            echo "docker-compose.yml not found in the current directory."
          fi

          # Check for docker-compose.yml in specific known directories (if applicable)
          if [ -f "path/to/docker-compose.yml" ]; then  # Replace with the actual path if needed
            echo "docker-compose.yml found in specified path."
          fi
          
          # Attempt to use the correct path for docker-compose.yml
          if [ -f "./docker-compose.yml" ]; then
            tar -cvf /tmp/173971303/W431XWtWYC.tar public/* ./docker-compose.yml
          else
            echo "docker-compose.yml not found, skipping the archive."
            exit 1  # Exit with status 1 if the file is not found
          fi
          
      - name: Copy public folder to remote server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "/tmp/173971303/W431XWtWYC.tar,docker-compose.yml"
          target: "/home/student01/my_gatsby_site/web"
