name : Remote SSH
on: 
  push:
      branches:
        - main
jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build --prefix-paths
          
      - name: Verify build
        run: ls -la public
           
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.PRIVATE_KEY }}" > ~/.ssh/deploy_key
          sudo chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H "${{ secrets.HOST }}" > ~/.ssh/known_hosts
          
      - name: SFTP upload
        run: sftp -i ~/.ssh/deploy_key ${{ secrets.USER }}@${{ secrets.HOST }} <<< $'cd site \n put -r public/*'
