name : Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build --prefix-paths
          
      - name: Verify build
        run: ls -la public
          
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}         
          username: ${{ secrets.USER }}     
          key: ${{ secrets.PRIVATEKEY }} 
          source: "public/"
          target: "site/newBranch"
          strip_components: 1

      - name: Finalize Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATEKEY }}
          script: |
            rm -rf site/mainBranch
            mv site/newBranch site/mainBranch
            mkdir site/newBranch
