name : Remote SSH
on: 
  push:
      branches:
        - main
jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build --prefix-paths
          
      - name: Verify build
        run: ls -la public
           
      - name: Deploy build to SSH server
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no" ./public/ student01@student01.wendell.tech:site

      - name: Atomic Deployment
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no student01@student01.wendell.tech << 'EOF'
          if ! docker info > /dev/null 2>&1; then
            cd site
            docker compose up -d --build
          fi
          mv html html_old || true
          mv html_new html
          rm -rf html_old 
          EOF
