name : Remote SSH
on: 
  push:
      branches:
        - main
jobs:
  build-and-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build
          
      - name: Verify build
        run: ls -la public

      - name: Copy files via SCP
        env:
            PRIVATE_KEY: ${{ secrets.PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOST  }}
            USER_NAME : ${{ secrets.USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${secrets.USER}@${secrets.HOST} '
