name : Remote SSH
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.1

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Install Project Dependencies
        run: npm install

      - name: Install Gatsby CLI
        run: npm install -g gatsby-cli

      - name: Build
        run: gatsby build --prefix-paths

      - name: Verify build
        run: ls -la public
      
      - name: Create random directory and tar file
        run: |
          RAND_DIR=$(mktemp -d /tmp/XXXXXX)  # Create a temporary directory
          TAR_FILE="$RAND_DIR/$(openssl rand -base64 12 | tr -d '/+').tar"  # Generate a random filename
          mkdir -p "$RAND_DIR"
          tar -cvf "$TAR_FILE" -C public .  # Use -C to change to public directory
          echo "Tar file created: $TAR_FILE"  # Print the created tar file for visibility
          echo $TAR_FILE >> $GITHUB_ENV  # Export the tar file path to an environment variable
          
      - name: Copy public folder to remote server
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          source: "${{ env.TAR_FILE }}"
          target: "/home/student01/my_gatsby_site/web"
